version: '2'

services:
  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - /usr/src/app/project/static
    command: python run.py
    depends_on:
      - postgres

  data:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    build: ./postgresql
    container_name: postgresql
    volumes_from:
      - data
    ports:
      - "5432:5432"
